Přidané a zrevidované akce set a unset meta pro hromadné přidávání a odebírání meta atributů

diff --git a/djvutool b/djvutool
--- a/djvutool
+++ b/djvutool
@@ -228,42 +228,6 @@ function potvrdit {
     esac
 }
 
-# TO REMOVE - meta
-function setmeta {
-	# Funkce pro nastavení meta atrinutů
-	# $1 - svazek
-	# $2 - identifikátor, klíčové slovo nebo soubor
-	# $3 - key
-	# $4 - obsah klíče
-	local SOURCE=$(${REALPATH} -m -P "${1}")
-	local FILE="${SOURCE##*/}"
-
-	if [ -f "${2}" ] ; then
-		echo "Importuji atributy ze souboru ${2}" >> /dev/stderr
-		# zpracování přes awk..
-		#${DJVUSED} ${1} -e "set-meta ${2}; save"
-		echo "Ještě není implementováno" >> /dev/stderr
-		exit 0
-	else
-		local NAMEPAGE=$(identifyname "${SOURCE}" "${2}")
-		if [ -z "${NAMEPAGE}" ] ; then
-			echo "Neplatný identifikátor stránky ${2}" >> /dev/stderr
-			exit 1
-		else
-			if [ "${3}" == "" ] ; then
-				if [ -f ${NAMEPAGE/.djvu/.meta} ] ; then
-					echo "Nastavuji klíč $3 do stránky $PAGE v souboru $1 s obsahem ${@:4}" >> /dev/stderr
-					${DJVUSED} ${1} -e "select ${NAMEPAGE}; set-meta ${NAMEPAGE/.djvu/.meta}; save"
-				fi
-			else
-				${DJVUSED} ${1} -e "select ${NAMEPAGE}; print-meta" > $TEMPDIR/${NAMEPAGE/.djvu/.meta}
-				echo "${@:3}" >> $TEMPDIR/${NAMEPAGE/.djvu/.meta}
-				${DJVUSED} ${1} -e "select ${NAMEPAGE}; set-meta $TEMPDIR/${NAMEPAGE/.djvu/.meta}; save"
-			fi
-		fi
-	fi
-}
-
 function printtext {
 	echo "${#1}" >> /dev/stderr
 	echo -e "${@}"
@@ -1201,6 +1165,8 @@ function djvurotate {
 	# $2 - číslo, nebo název strany která se má rotovat
 	# $3 - hodnota rotace
 #	echo "$*" >> /dev/stderr
+	local SOURCE=$(${REALPATH} -m -P "${1}")
+	local FILE="${SOURCE##*/}"
 	local INFO="""
 Uvedenou hodnotu rotace nelze akceptovat. Rotaci lze nastavit buď 
 absolutně, a nebo relativně (pootočit o 90°). AKceptované hodnoty:
@@ -1224,48 +1190,45 @@ Každá jiná hodnota parametru je ignorována."""
 				local IDPAGE=${TEMP##+([[:blank:]])}
 #				echo "rotate: po ořezání -${IDPAGE}-"
 			;;
-			*) echo "Neplatný parametr rotace - ${2}" >> /dev/stderr
+			*) printf "%s - is not valid rotate VALUE" "${2}" >> /dev/stderr
 				exit 1
 			;;
 		esac
 	else
-#		echo "Rotuji dokument globálně.. ${PARAMS}" >> /dev/stderr
 		case "${PARAMS}" in
-			0|1|2|3|180|left|right) #  echo "Jak mám otáčet $1" >> /dev/stderr
-				local ROTATE="${PARAMS}"
+			0|1|2|3|180|left|right) local ROTATE="${PARAMS}"
 			;;
-			*) echo "Neplatný parametr rotace - ${PARAMS}" >> /dev/stderr
+			*) printf "%s - is not valid rotate VALUE" "${PARAMS}" >> /dev/stderr
 				exit 1
 			;;
 		esac
 	fi
-#	echo "rotate: ${IDPAGE} - ${ROTATE}" >> /dev/stderr
 
 	if $(identifybundle "${1}") ; then
 		if [ -z "${IDPAGE}" ] ; then
 			case "${ROTATE}" in
-				0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${1}"
+				0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${SOURCE}"
 				;;
-				left) ${DJVUSED} -e "set-rotation +1; save" "${1}"
+				left) ${DJVUSED} -e "set-rotation +1; save" "${SOURCE}"
 				;;
-				right) ${DJVUSED} -e "set-rotation -1; save" "${1}"
+				right) ${DJVUSED} -e "set-rotation -1; save" "${SOURCE}"
 				;;
-				180) ${DJVUSED} -e "set-rotation +2; save" "${1}"
+				180) ${DJVUSED} -e "set-rotation +2; save" "${SOURCE}"
 				;;
 				*) echo "${INFO}" >> /dev/stderr
 				;;
 			esac
 		else
-			echo "Dokument je typu DjVu single page. Parametr ${IDPAGE} nemá význam, chcete pokračovat v rotaci?" >> /dev/stderr
+			printf "DjVu file is single page. Param %s is non sense, continue in rotate?" "${IDPAGE}" >> /dev/stderr
 			if $(potvrdit) ; then
 				case "${ROTATE}" in
-					0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${1}"
+					0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${SOURCE}"
 					;;
-					left) ${DJVUSED} -e "set-rotation +1; save" "${1}"
+					left) ${DJVUSED} -e "set-rotation +1; save" "${SOURCE}"
 					;;
-					right) ${DJVUSED} -e "set-rotation -1; save" "${1}"
+					right) ${DJVUSED} -e "set-rotation -1; save" "${SOURCE}"
 					;;
-					180) ${DJVUSED} -e "set-rotation +2; save" "${1}"
+					180) ${DJVUSED} -e "set-rotation +2; save" "${SOURCE}"
 					;;
 					*) echo "${INFO}" >> /dev/stderr
 					;;
@@ -1276,16 +1239,16 @@ Každá jiná hodnota parametru je ignorována."""
 		fi
 	else
 		if [ -z "${IDPAGE}" ] ; then
-			echo "Při globálním natočení stránek dokumentu dávejte pozor, zda-li nastavujete absolutní hodnotu natočení, nebo, zda-li otáčíte stránky relativně (left/right). Při točení se upravuje natočení všech stránek. Buďte tedy při této operaci opatrní a raději si předem zkontrolujte, zda-li tím neovlivníte i některou ze stránek. Pokud ano, pak zvolte buť relativní parametr natočení, nebo ji pak otočte do správné pozice dodatečně."
+			echo "Warning: If you want c a global orientation of pages Při globálním natočení stránek dokumentu dávejte pozor, zda-li nastavujete absolutní hodnotu natočení, nebo, zda-li otáčíte stránky relativně (left/right). Při točení se upravuje natočení všech stránek. Buďte tedy při této operaci opatrní a raději si předem zkontrolujte, zda-li tím neovlivníte i některou ze stránek. Pokud ano, pak zvolte buť relativní parametr natočení, nebo ji pak otočte do správné pozice dodatečně."
 			if $(potvrdit) ; then
 				case "${ROTATE}" in
-					0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${1}"
+					0|1|2|3)  ${DJVUSED} -e "set-rotation ${ROTATE}; save" "${SOURCE}"
 					;;
-					left) ${DJVUSED} -e "set-rotation +1; save" "${1}"
+					left) ${DJVUSED} -e "set-rotation +1; save" "${SOURCE}"
 					;;
-					right) ${DJVUSED} -e "set-rotation -1; save" "${1}"
+					right) ${DJVUSED} -e "set-rotation -1; save" "${SOURCE}"
 					;;
-					180) ${DJVUSED} -e "set-rotation +2; save" "${1}"
+					180) ${DJVUSED} -e "set-rotation +2; save" "${SOURCE}"
 					;;
 					*) echo "${INFO}" >> /dev/stderr
 					;;
@@ -1297,18 +1260,18 @@ Každá jiná hodnota parametru je ignorována."""
 #			echo "Je třeba provést identifikaci stránky ${IDPAGE}"
 			local NAMEPAGE=$(identifyname "${1}" "${IDPAGE}")
 			if [ -z "${NAMEPAGE}" ] ; then
-				echo "Stránka ${IDPAGE} ve svazku ${1} není" >> /dev/stderr
+				printf "Page %s is not valid for file %s" "${IDPAGE}" "${FILE}" >> /dev/stderr
 				exit 1
 			else
-				log 1 "Otáčím stránku ${NAMEPAGE}"
+				printf "Change orientation page %s in %s by %s" "${NAMEPAGE}" "${FILE}" "${ROTATE}" >> ${LOG}
 				case "${ROTATE}" in
-					0|1|2|3)  ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation ${ROTATE}; save" "${1}"
+					0|1|2|3)  ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation ${ROTATE}; save" "${SOURCE}"
 					;;
-					left) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation +1; save" "${1}"
+					left) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation +1; save" "${SOURCE}"
 					;;
-					right) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation -1; save" "${1}"
+					right) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation -1; save" "${SOURCE}"
 					;;
-					180) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation +2; save" "${1}"
+					180) ${DJVUSED} -e "select '${NAMEPAGE}'; set-rotation +2; save" "${SOURCE}"
 					;;
 					*) echo "${INFO}" >> /dev/stderr
 					;;
@@ -1821,6 +1784,124 @@ function djvumove {
 # Má se přesouvat kupředu
 }
 
+function range {
+	# 1,2,3-9,10-20
+	case "${1:0:1}" in
+		[[:digit:]]) local INPUTARRAY=( ${1//,/ } )
+			for i in ${INPUTARRAY[@]} ; do
+				if [[ "$i" =~ "-" ]] ; then
+					seq ${i//-/ }
+				else
+					seq ${i} ${i}
+				fi
+			done | sort -u
+		;;
+		*) printf "range: FAIL - range of pages must be set only from order numbers, commas and hyphens.\n" >> /dev/stderr
+		exit 1
+		;;
+	esac
+}
+
+function setmeta {
+	local SOURCE=$(${REALPATH} -m -P "${1}")
+	local FILE="${SOURCE##*/}"
+	local TEMPFILE=$(tempfile -d ${TEMPDIR} -s .meta)
+	local CHARSET="${2}"
+	if [ "${CHARSET%%\ *}" == "all" ] ; then
+		local ITEM="${CHARSET#* }"
+		local KEY=(${ITEM})
+		if [ "${#KEY[@]}" -lt "2" ] ; then
+			printf "setmeta: FAIL - you must set meta attribute key and any value for it.\n"
+			exit 1
+		else
+			for i in $(seq $(lastpage "${SOURCE}")) ; do
+				printf "set meta: Set meta attribute key %s into all pages in DjVu bundle %s\n" "${KEY[0]}" "${FILE}" >> ${LOG}
+				printmeta "${SOURCE}" "$i" | grep -v '^[#.]\|^$' > ${TEMPFILE}
+				ed ${TEMPFILE} 2>/dev/null <<-EOF
+/${KEY}
+d
+w
+q
+EOF
+				ed ${TEMPFILE} 2>/dev/null <<-EOF
+i
+${ITEM}
+.
+w
+q
+EOF
+				${DJVUSED} "${SOURCE}" -e "select $i; set-meta ${TEMPFILE}" -s
+			done 1>/dev/null
+		fi
+	else
+		local RANGE=($(range "${CHARSET%%\ *}"))
+		local ITEM="${CHARSET#* }"
+		local KEY=(${ITEM})
+		for i in ${RANGE[@]} ; do
+			# export meta pro stránku $i
+			# příkaz ed pro editaci..
+			printf "set meta: Set meta attribute key %s into page %s in DjVu bundle %s\n" "${KEY[0]}" "$i" "${FILE}" >> ${LOG}
+			printmeta "${SOURCE}" "$i" | grep -v '^[#.]\|^$' > ${TEMPFILE}
+			ed ${TEMPFILE} 2>/dev/null <<-EOF
+/${KEY}
+d
+w
+q
+EOF
+			ed ${TEMPFILE} 2>/dev/null <<-EOF
+i
+${ITEM}
+.
+w
+q
+EOF
+			${DJVUSED} "${SOURCE}" -e "select $i; set-meta ${TEMPFILE}" -s
+		done 1>/dev/null
+	fi
+	return 0
+}
+
+
+function unsetmeta {
+	local SOURCE=$(${REALPATH} -m -P "${1}")
+	local FILE="${SOURCE##*/}"
+	local TEMPFILE=$(tempfile -d ${TEMPDIR} -s .meta)
+	local CHARSET="${2}"
+	if [ "${CHARSET%%\ *}" == "all" ] ; then
+		local ITEM="${CHARSET#* }"
+		local KEY=(${ITEM})
+		printf "unset meta: Remove attribute key %s from all pages DjVu bundle %s\n" "${KEY[0]}" "${FILE}" >> ${LOG}
+		for i in $(seq $(lastpage "${SOURCE}")) ; do
+			printmeta "${SOURCE}" "$i" | grep -v '^[#.]\|^$' > ${TEMPFILE}
+			ed ${TEMPFILE} 2>/dev/null <<-EOF
+/${KEY}
+d
+w
+q
+EOF
+			${DJVUSED} "${SOURCE}" -e "select $i; set-meta ${TEMPFILE}" -s
+		done  1>/dev/null
+	else
+		local RANGE=($(range "${CHARSET%%\ *}"))
+		local ITEM="${CHARSET#* }"
+		local KEY=(${ITEM})
+		for i in ${RANGE[@]} ; do
+			# export meta pro stránku $i
+			# příkaz ed pro editaci..
+			printf "unset meta: Remove attribute key %s from page %s\n" "${KEY[0]}" "$i" >> ${LOG}
+			printmeta "${SOURCE}" "$i" | grep -v '^[#.]\|^$' > ${TEMPFILE}
+			ed ${TEMPFILE} 2>/dev/null <<-EOF
+/${KEY}
+d
+w
+q
+EOF
+			${DJVUSED} "${SOURCE}" -e "select $i; set-meta ${TEMPFILE}" -s
+		done  1>/dev/null
+	fi
+	return 0
+}
+
 function djvuinfo {
 	# $1 - soubor
 	# $2 - parametry
@@ -2179,7 +2260,7 @@ Použitelné parametry:
   Print informations about DjVu bundle. Without parameters return number of pages.
   If is DjVu file 'single-page', return 'none'.
 
-  [1m${0##*/}[0m [volby] {DjVu file} info [SUBKEY [<num>|<name>]]
+  [1m${0##*/}[0m <DjVu> info [SUBKEY [<num>|<name>]]
 
          num  - order number of page in DjVu bundle
          name - name of page in DjVu bundle
@@ -2219,16 +2300,6 @@ Použitelné parametry:
     přejmenování - za název se přidá podtržítko a pořadové číslo.
 """
 		;;
-# ODSTRANIT VVVV
-		keywords-list) echo """akce [1mlist[0m
-
-Zrušeno, nahrazeno akcí info
-
-  [4mSeznam stránek v DjVu souboru[24m.
-
-  [1m${0##*/}[0m [volby] <file> list
-"""
-		;;
 		keywords-fore) help move
 		;;
 		keywords-fore1) echo """akce [1mfore[0m
@@ -2266,79 +2337,65 @@ Zrušeno, nahrazeno akcí info
   svazku jedinečné.
 """
 		;;
-		keywords-rotate) echo """akce [1mrotate[0m
+		keywords-rotate) echo """
+  KEYWORD [1mrotate[0m
 
-  Úprava výchozího natočení DjVu stránek.
+  For change of default orientation page in DjVu file.
 
-  [1m${0##*/}[0m [volby] <svazek> rotate {<num>|<name>} <value>
+  [1m${0##*/}[0m [option] <DjVu> rotate {<num>|<name>} <VALUE>
 
-         num   - pořadové číslo stránky
-         name  - jméno stránky
-         value - parametr jak má být stránka natočena
+         num   - order of page to change in DjVu bundle
+         name  - name of page to change in DjVu bundle
 
-[1mParametry[0m
-  O - nastaví stránku do výchozí pozice
-  1 - natočí stránku o 90° vpravo
-  2 - natočí stránku vzůru nohama 
-  3 - natočí stránku o 90° vlevo
-  left - pootočí stránku o 90° směrem doleva
-  right - pootočí stránku o 90° směrem doprava
-  180 - pootočí stránku o 180°
+Options:
+    -f|--force   Force rotate without any questions
 
-[3mPoznámka:[23m
-          Není-li uveden identifikátor stránky, bude parametrem
-          nastaveno globální natočení pro všechny stránky dokumentu.
+  VALUE:
+             0 - normal orientation (0°)
+             1 - rotate page 90° to right
+             2 - rotate page 180°
+             3 - rotate page 90° to left (270°)
+          left - rotate page 90° in left direction
+         right - rotate page 90° in right direction
+           180 - turn the page on the contrary
+
+[3mWarning:[23m
+  * If is not any identificator of page, do set global orientation for all DjVu bundle.
 """
 		;;
-# ODSTRANIT VVVV
-		keywords-set) echo """akce [1mset[0m
-
-Zrušeno - nahrazeno akcemi edit a import
-
-  [4mNastavení meta atributů[24m DjVu stránky, resp. celého svazku
-
-  [1m${0##*/}[0m [volby] <svazek> set {<num>|<name>} {<file>|<key> <value>}
-
-  [1m${0##*/}[0m [volby] <svazek> set {<file>|<key> <value>}
-
-         num   - pořadové číslo stránky
-         name  - jméno stránky
-         file  - soubor s meta atributy
-         key   - jméno meta atributu
-         value - hodnota meta atributu
-
-Nejběžnější atributy (key):
-       Title - Název DjVu dikumentu
-     Creator - Jméno tvůrce DjVu dokumentu
-CreationDate - Čas vytvoření dokumentu
-    Keywords - Klíčová slova pro indexaci DjVu dokumentu
-      annote - Poznámka k dokumentu
-
-[3mPoznámka:[23m
-  Další viz akce [2mprint[22m, [2mexport[22m, [2mimport[22m, [2munset[22m a manuál k tomuto skriptu.
-"""
+		keywords-set) help keywords-meta
 		;;
-# ODSTRANIT VVVV
-		keywords-unset) echo """akce [1munset[0m
+		keywords-unset) help keywords-meta
+		;;
+		keywords-meta) echo """
+  KEYWORD [1mset[0m or [1munset[0m
 
-Zrušeno - nahrazeno akcí edit a import
+  Keywords [2mset[22m or [2munset[22m work only with one meta attribute key.
+  For view meta attribute use keyword [2minfo[22m and [2mexport[22m for output in format which is usable to [2mimport[22m. You may attributs [2medit[22m rightly too.
 
-  [4mOdstranění meta atributů[24m DjVu stránky, resp. celého svazku
+  [1m${0##*/}[0m <DjVu> unset meta {all|<RANGE>} <KEY>
 
-  [1m${0##*/}[0m [volby] <svazek> unset {<num>|<name>} <key>
+[3mNotice:[23m
+  * If is not set any KEY, do it nothing.
 
-  [1m${0##*/}[0m [volby] <svazek> unset <key>
+  [1m${0##*/}[0m <DjVu> set meta {all|<RANGE>} <KEY> <VALUE>
 
-         num   - pořadové číslo stránky
-         name  - jméno stránky
-         key   - jméno meta atributu
+    all - set some meta attribute into all pages in DjVu bundle
+  RANGE - Range use comma for separate numbers order positions of pages in DjVu bundle, and hyphen for limitation from-to page range.
 
-[1mDávejte pozor[0m - akce je nevratná !
-  Akce dovoluje odstranit nejenom vybraný atribut, ale také všechny další,
-  proto ji využívejte nanejvýš opatrně. S meta atributy pracujte raději
-  prostřednictvím souborů zpracovávaných při akcích [2mexport[22m a [2mimport[22m.
-  Pro ověření klíče, před jeho zrušením využijte akci [2mprint[22m. Nový obsah
-  klíče lze nastavit přes akci [2mset[22m.
+Example using RANGE:
+
+    [1m${0##*/}[0m bundle.djvu set meta 1,3,7-12 Creator 'Thomas Jefferson'
+
+Commonly KEYS:
+                   [3mTitle[23m - Title of DjVu page
+                 [3mCreator[23m - Creator DjVu bundle, or DjVu page
+            [3mCreationDate[23m - Time of create DjVu page
+                [3mKeywords[23m - Keywords for indexation DjVu file
+                  [3mannote[23m - Annotation about origin page (in ex.)
+[3mNotice:[23m
+  * KEY is single word without diacritical chars, and spaces
+  * VALUE is normal text string
 """
 		;;
 # ODSTRANIT VVVV
@@ -3124,6 +3181,25 @@ done
 						exit 0
 					;;
 					rename)   # ToDo - zpracovat ${CHARSTRING}
+						exit 1
+					;;
+					set) case "${CHARSTRING%% *}" in
+							meta) setmeta "${FILE}" "${CHARSTRING#* }"
+							;;
+							*) help keyword-meta
+							;;
+						esac
+						exit 0
+					;;
+					unset) case "${CHARSTRING%% *}" in
+							meta) unsetmeta "${FILE}" "${CHARSTRING#* }"
+							;;
+							*) help keyword-meta
+							;;
+						esac
+						exit 0
+					;;
+					view) djview "${FILE}" &
 						exit 1
 					;;
 					*) help keywords && exit 0
